[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300

[variables]
PORT = "80"